### ISSUE TITLE
WebSocket is not Defined

### ISSUE THREAD

**Issue by Natanil** [gamestdio/colyseus.js#32]
I have been trying a lot to fix this issue but unfortunately i get this error all the time : 

/Users/natanil/Node_Projects/Client_Example_colyseus/colyseus-examples/node_modules/@gamestdio/websocket/lib/index.js:70
 */WebSocketClient.CONNECTING=WebSocket.CONNECTING;/**
                              ^

ReferenceError: WebSocket is not defined
    at Object.<anonymous> (/Users/natanil/Node_Projects/Client_Example_colyseus/colyseus-examples/node_modules/@gamestdio/websocket/lib/index.js:70:31)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/natanil/Node_Projects/Client_Example_colyseus/colyseus-examples/node_modules/colyseus.js/lib/Connection.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:702:30)

**Comment by endel** [comment]
Hi @Natanil, the `colyseus.js` client works out-of-the-box only on browser environments. It looks like you're using it in a Node environment, though? Can you describe your environment?

To be able to run inside Node.js, you'd need a `WebSocket` implementation since Node doesn't provide one. e.g. `global.WebSocket = require("uws")`

Cheers

**Comment by Natanil** [comment]
Thanks. Yep i was trying to run this in node . 
So Could you please tell me how exactly im supposed to do so for running on browser environment?

**Comment by seiyria** [comment]
You use colyseus for nodejs, and colyseus.js for the browser.

**Comment by vapurrmaid** [comment]
@Natanil @endel  - Should this issue now be closed?
