### ISSUE TITLE
Error on JavaScript client

### ISSUE THREAD

**Issue by castrolol** [gamestdio/colyseus.js#40]
I can't use the `colyseus.js` on pure JS or in webpack
the error above occurs

```
index.js:5 Uncaught DOMException: Failed to construct 'WebSocket': The URL contains a fragment identifier ('default&requestId=1'). Fragment identifiers are not allowed in WebSocket URLs.
    at Connection.open (http://localhost:5555/bundle.js:21209:53)
    at Room.connect (http://localhost:5555/bundle.js:21365:26)
    at Client.onMessageCallback (http://localhost:5555/bundle.js:20057:19)
    at Connection.onMessageCallback (http://localhost:5555/bundle.js:21218:129)

```

my client code :
```js
 this.client = new Colyseus.Client('ws://localhost:5555');

 this.client.connect();

 this.chatRoom = this.client.join('chat', { channel: window.location.hash || '#default' });

```

**Comment by oyed** [comment]
Try removing the hashtag (`#`) from your `channel` - I might be wrong but I believe Colyseus uses the hashtag to pass the `join` data to the websocket request, so adding your own is killing it.

**Comment by oyed** [comment]
```js
this.chatRoom = this.client.join('chat', { channel: window.location.hash.substring(1) || 'default' });
```

**Comment by castrolol** [comment]
Oh Man Thank You!

It works... Save about 3hrs work!

**Comment by oyed** [comment]
@castrolol No problem - feel free to close this issue and if you have any other issues open another one (Or join us on [Gitter](https://gitter.im/gamestdio/colyseus))
